# Generated by Django 4.1.6 on 2023-02-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_remove_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymoususer',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='anonymous_identifier',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
