# Generated by Django 4.1.6 on 2023-02-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_rename_name_anonymoususer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='anonymous_identifier',
            field=models.CharField(max_length=255),
        ),
    ]
