# Generated by Django 4.1.6 on 2023-02-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0007_alter_anonymoususer_anonymous_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='anonymous_identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='anonymoususer',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
