# Generated by Django 4.1.6 on 2023-02-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0008_alter_anonymoususer_anonymous_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
