# Generated by Django 4.1.6 on 2023-02-27 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0010_alter_anonymoususer_anonymous_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='anonymous_identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
