# Generated by Django 4.1.6 on 2023-02-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('institution_link', models.CharField(max_length=100)),
                ('certificate_link', models.CharField(max_length=100)),
                ('validations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('years_exp', models.FloatField(default=0.0)),
                ('validations', models.IntegerField(default=0)),
            ],
        ),
    ]
