# Generated by Django 4.1.6 on 2023-02-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0003_alter_technology_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='technoloy',
            new_name='technology',
        ),
    ]
