# Generated by Django 4.1.6 on 2023-02-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0005_study_image_alter_technology_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='study_images'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tech_images'),
        ),
    ]
