# Generated by Django 4.1.6 on 2023-02-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0006_alter_study_image_alter_technology_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='certificate_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='institution_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
