# Generated by Django 4.1.6 on 2023-03-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0009_alter_validation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
