# Generated by Django 4.1.6 on 2023-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_like_comment_alter_like_post_alter_like_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='github_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
