# Generated by Django 4.1.6 on 2023-02-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_post_project_link_alter_post_github_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='project_link',
            new_name='website_link',
        ),
    ]
