# Generated by Django 4.1.6 on 2023-02-06 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_anonymoususer'),
        ('Post', '0007_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.anonymoususer'),
        ),
        migrations.AddField(
            model_name='review',
            name='anonymous_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.anonymoususer'),
        ),
    ]
