# Generated by Django 4.1.6 on 2023-02-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_like_anonymous_user_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/posts_images/<django.db.models.fields.CharField>'),
        ),
    ]
