# Generated by Django 4.1.6 on 2023-02-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_remove_comment_likes_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='anonymous_user',
        ),
        migrations.AddField(
            model_name='like',
            name='anonymous_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
