# Generated by Django 4.1.6 on 2023-02-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_remove_like_anonymous_user_like_anonymous_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='developed_for',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images'),
        ),
    ]
