# Generated by Django 4.1.6 on 2023-02-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_post_developed_for_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='developed_for_link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
