# Generated by Django 4.1.6 on 2023-02-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_remove_post_num_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
