# Generated by Django 4.1.6 on 2023-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_remove_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='Completed', max_length=25),
        ),
    ]
