# Generated by Django 4.1.6 on 2023-03-01 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0017_post_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('post', 'user')},
        ),
    ]
