# Generated by Django 4.1.6 on 2023-03-12 01:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0011_alter_anonymoususer_anonymous_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0018_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('post', 'user'), ('post', 'anonymous_user')},
        ),
    ]
